feat: update msg to follow new definitions
decentraland/adr pull request #149
Opened 2022-12-12 17:00 UTC by Julieta11

2022-12-12 17:51 UTC, menduz commented
Hi Juli, `status: Final` is meant for implemented ADR that became read-only, kind of a written-in-stone thing. Would you mind changing it to `Review` or `Draft` until fully deployed? In that moment, I recommend to use `Living` instead of `Final` so we can update it as needed

2022-12-12 19:02 UTC, marianogoldman requested changes

2022-12-13 14:22 UTC, Julieta11 commented on content/ADR-137-new-friend-request.md
> +renderer->kernel: GetFriendRequests(SendFriendRequestPayload{ userId:'0x...', messageBody='hello!' })
hi @marianogoldman! would you mind telling me specifically where would you add the parentheses? I read your comments and I don't see it hah 🥲

I'm just following what it was like before my changes. I think it follows the following reasoning, does it make sense to you?

<img width="655" alt="image" src="https://user-images.githubusercontent.com/42394626/207357235-9c29c9d6-cc66-40cb-98c3-dfadc81b4eee.png">

2022-12-13 14:24 UTC, Julieta11 commented on content/ADR-137-new-friend-request.md
> +## Get Friend Request List
There was a definition change that led to that message being discarded.

2022-12-14 12:59 UTC, marianogoldman commented on content/ADR-137-new-friend-request.md
> +renderer->kernel: GetFriendRequests(SendFriendRequestPayload{ userId:'0x...', messageBody='hello!' })
Oh, I thought there should be a parenthesis after `SendFriendRequestPayload` and before the `{...}`, but perhaps not needed. I don't even know what the language is and whether the syntax is correct. So please disregard if that is correct.

2022-12-14 13:00 UTC, marianogoldman approved these changes
If the parenthesis things are ok as they are, then 👍

2022-12-14 14:44 UTC, merged