feat: update adr 41
decentraland/adr pull request #23
Opened 2021-09-23 16:32 UTC by nachomazzara

2021-09-23 16:48 UTC, pentreathm approved these changes

2021-09-24 12:23 UTC, pentreathm commented on docs/ADR-41-collection-items-approval-flow-enhancement.md
> +- The catalyst will accept entities (items) if they content hashes are in the blockchain. The entity will be deployed by anyone. Changes will be needed [here](https://github.com/decentraland/catalyst
```suggestion
- The catalyst will accept entities (items) if their content hashes are in the blockchain. The entity will be deployed by anyone. Changes will be needed [here](https://github.com/decentraland/catalyst/blob/3098701a42f0656dc595e653694abf4f7f418bee/content/src/service/access/AccessCheckerForWearables.ts#L119). Catalysts will need to hash all the entries of the entitiy except from the timestamp (`entitiyHashWithoutTimestamp`). This way, when the user deploys the entity to the catalyst, the catalyst will check if the item's content hash in the blockchain is equal to the `entitiyHashWithoutTimestamp` in the same timestamp/block where the deployment occurs.
```

2021-09-24 12:26 UTC, pentreathm approved these changes

2021-09-24 12:26 UTC, menduz requested changes

2021-09-24 12:26 UTC, menduz commented on docs/ADR-41-collection-items-approval-flow-enhancement.md
> +- The catalyst will accept entities (items) if they content hashes are in the blockchain. The entity will be deployed by anyone. Changes will be needed [here](https://github.com/decentraland/catalyst
```suggestion
- The catalyst will accept entities (items) if the content hashes are reflected in the blockchain. The entity will be deployed without signature restrictions, that is, any account can sign the deployment. Changes will be needed [here](https://github.com/decentraland/catalyst/blob/3098701a42f0656dc595e653694abf4f7f418bee/content/src/service/access/AccessCheckerForWearables.ts#L119). Catalysts will need to hash the metadata and the contents of the entitiy as stated in [ADR-32](ADR-32-wearable-committee-reverts.md) (`contentHash`). This way, when the user deploys the entity to the catalyst, the catalyst will check if the item's content hash in the blockchain is equal to the `contentHash` in the same timestamp/block where the deployment occurs.
```

2021-09-24 12:27 UTC, menduz commented on docs/ADR-41-collection-items-approval-flow-enhancement.md
> +- The catalyst will accept entities (items) if they content hashes are in the blockchain. The entity will be deployed by anyone. Changes will be needed [here](https://github.com/decentraland/catalyst
Added correct hashing to match ADR-32

2021-09-24 13:04 UTC, merged